version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'
  crawler_back:
      build: ./search_engine_crawler
      container_name:search_engine_crawler
      environment:
        -  'MONGO=???' 
        -  'MONGO_PORT=27017'
        -  'RMQ_HOST=???'
        -  'RMQ_QUEUE=???'
        -  'RMQ_USERNAME=???'
        -  'RMQ_PASSWORD=???'
        -  'CHECK_INTERVAL=???'
        -  'EXCLUDE_URLS=???'
  crawler_front:
      build: ./search_engine_ui
      container_name:search_engine_ui
      environment:
        -  'MONGO=???' 
        -  'MONGO_PORT=27017'
            
        
    #volumes:
      #- './enabled_plugins:/etc/rabbitmq/enabled_plugins'
      #- './rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro'
      #- './autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez'

volumes:
  mongodb-data: {}