version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - mongo_db:/data/db
    networks:
      - back_net
  ui:
    build: .
    image: mzabolotnov/ui_crawler:1.0
    ports:
      - 8000:8000/tcp
    networks:
      - front_net
      - back_net

volumes:
  mongo_db:

networks:
  front_net:
    driver: bridge
    ipam:
       config:
        - subnet: 10.0.1.0/24
  back_net:
      driver: bridge
      ipam:
        config:
         - subnet: 10.0.2.0/24

