apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
 name: monitoring-{{ .Release.Name }}-{{ .Chart.Name }}
 namespace: {{.Release.Namespace}}
 labels:
   app: crawler-service-monitor
spec:
   selector:
    matchLabels:
     app: crawler
     component: crawler
     release: {{ .Release.Name }}
   endpoints:
   - interval: 15s
     path: /metrics
     port: crawlerport
   namespaceSelector:
    matchNames:
    - {{.Release.Namespace}}
