cloud_id                 = "b1g730q1t94lbv6lagff"
folder_id                = "b1g0m7gthn4g87f5103c"
zone                     = "ru-central1-a"
image_id                 = "fd80viupr3qjr5g6g9du" #ubuntu18LTS, yc compute image list --folder-id standard-images
public_key_path          = "~/.ssh/id_rsa.pub"
privat_key_path          = "~/.ssh/id_rsa"
subnet_id                = "e9bj6e9d2armga9ud6ml"#моя зона для ru-central1-a, yc vpc subnet list
service_account_key_file = "../../../../key2.json"
count_instance           = 3
