---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-0
  labels:
    type: local
spec:
  storageClassName: master-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdb1/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-1
  labels:
    type: local
spec:
  storageClassName: master-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdb1/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-2
  labels:
    type: local
spec:
  storageClassName: master-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdb1/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-0
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdc1/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdc1/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-2
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disks/vdc1/data"
