{
 "title": "Crawler dashboard Copy",
 "time": { "from": "2021-08-11T12:59:27.830Z", "to": "2021-08-11T17:18:04.542Z" },
 "panels": [
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "количество обработанных ботом страниц",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "Время затраченное ботом на загрузку и обработку web-страниц",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum"
    },
    { "expr": "crawler_page_parse_time_sum" }
   ]
  },
  { "title": "UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "UI-количество обработанных запросов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "web_pages_served" }
   ]
  },
  {
   "title": "UI - время генерации веб-страниц, учитывая время обработки запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "web_page_gen_time_sum" }
   ]
  }
 ]
}