---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: rabbitmq
      release: {{ .Release.Name }}

  template:
    metadata:
      name: rabbitmq
      labels:
        app: crawler
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: rabbitmq:3-management-alpine
        name: rabbitmq
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var
      volumes:
      - name: rabbitmq-persistent-storage
        emptyDir: {}
