---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
